import Head from "next/head";
import Image from "next/image";
import Carousel from "react-multi-carousel";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import "react-multi-carousel/lib/styles.css";
import Slider from "../components/Slider";
import Main from "../components/Main";
import { Context } from "../context";
import { useEffect, useState } from "react";
import axios from "axios";
import { app, db, dbRef } from "../firebase/initFirebase";
import { getDatabase, ref, query, limitToLast, get, child, limitToFirst } from "firebase/database";

export default function Home({ data }) {
  const [criteriaSlider, setCriteriaSlider] = useState("");
  // const db = getDatabase()
  useEffect(() => {
    get(query(dbRef, limitToFirst(1))).then(snapShot=>{
      const arr = Object.values(snapShot.val());
      console.log(arr);
    })
    
  }, []);

  return (
    <Context.Provider
      value={{
        data: data.data,
        setCriteriaSlider: setCriteriaSlider,
        criteriaSlider: criteriaSlider,
        sliderData: data.sliderResult,
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider />
      <Main />
    </Context.Provider>
  );
}

export const getServerSideProps = async (ctx) => {
  const res = await axios.get(`http://localhost:3000/api/getData`);
  return { props: { data: res.data } };
};
